# Generated by Django 4.0.1 on 2022-01-29 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_vendor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendor',
            options={'verbose_name': 'Vendor', 'verbose_name_plural': 'Vendors'},
        ),
    ]
