# Generated by Django 4.0.1 on 2022-01-29 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_vendor_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='address',
            name='city_area',
        ),
        migrations.RemoveField(
            model_name='address',
            name='country_area',
        ),
        migrations.RemoveField(
            model_name='address',
            name='last_name',
        ),
    ]
