# Generated by Django 4.0.1 on 2022-02-02 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_rename_first_name_address_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='default_billing_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing', to='account.address'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='default_shipping_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping', to='account.address'),
        ),
    ]
