# Generated by Django 4.0.1 on 2022-02-08 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_address_number_address_unit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='number',
            new_name='house_number',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='unit',
            new_name='house_unit',
        ),
    ]
