# Generated by Django 4.0.2 on 2022-02-22 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_historicalcredit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='phone',
            new_name='address_phone',
        ),
    ]
