# Generated by Django 4.0.2 on 2022-02-22 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_rename_phone_address_address_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='kind',
            field=models.CharField(blank=True, choices=[('billing', 'Billing'), ('shipping', 'Shipping')], max_length=25, null=True),
        ),
    ]
