# Generated by Django 4.0.2 on 2022-02-23 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_address_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='house_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='house_unit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
