# Generated by Django 4.0.2 on 2022-02-24 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_alter_address_house_number_alter_address_house_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='social_media_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
