# Generated by Django 4.0.2 on 2022-02-27 04:13

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_customuser_social_media_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone_2',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
