# Generated by Django 4.0.2 on 2022-03-11 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0024_alter_vendor_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_online_manager',
            field=models.BooleanField(default=False),
        ),
    ]
