# Generated by Django 4.0.2 on 2022-04-03 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0027_credit_book_sum_credit_craft_sum_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='book_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='credit',
            name='craft_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicalcredit',
            name='book_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicalcredit',
            name='craft_count',
            field=models.IntegerField(default=0),
        ),
    ]
