# Generated by Django 4.0.2 on 2022-04-03 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0028_credit_book_count_credit_craft_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='order_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicalcredit',
            name='order_count',
            field=models.IntegerField(default=0),
        ),
    ]
