# Generated by Django 4.0.2 on 2022-04-03 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0029_credit_order_count_historicalcredit_order_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='orderlines_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicalcredit',
            name='orderlines_count',
            field=models.IntegerField(default=0),
        ),
    ]
