# Generated by Django 4.0.2 on 2022-04-07 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0030_credit_orderlines_count_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ('is_superuser', 'is_manager', 'last_name', 'first_name')},
        ),
    ]
