# Generated by Django 4.0.1 on 2022-02-16 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slogan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slogan', models.CharField(max_length=350)),
                ('author', models.CharField(default='', max_length=100)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
