# Generated by Django 4.0.2 on 2022-02-27 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='tag',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
