# Generated by Django 4.0.1 on 2022-01-12 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zarinpal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='ref_id',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
