# Generated by Django 4.0.2 on 2022-02-27 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zarinpal', '0004_payment_order_payment_payment_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='url',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
