# Generated by Django 4.0 on 2021-12-14 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='file/upload/')),
                ('type', models.CharField(choices=[('.excel', 'xls'), ('.pdf', 'pdf')], default='xls', max_length=8)),
            ],
        ),
    ]
