# Generated by Django 4.0 on 2021-12-18 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_importsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='importsession',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
