# Generated by Django 4.0.2 on 2022-02-21 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0002_refund'),
    ]

    operations = [
        migrations.AddField(
            model_name='refund',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
