# Generated by Django 4.0.2 on 2022-04-07 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_alter_ticket_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
