# Generated by Django 4.0.2 on 2022-04-07 08:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_ticket_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='rank',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
