# Generated by Django 4.0.2 on 2022-04-07 08:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_alter_ticket_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.CharField(choices=[('normal', 'Normal'), ('medium', 'Medium'), ('high', 'High')], default='normal', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='rank',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
