# Generated by Django 4.0 on 2021-12-25 11:35

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0006_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, default='', max_length=128, region=None)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('unfulfilled', 'Unfulfilled'), ('fulfilled', 'Fulfilled'), ('canceled', 'Canceled')], default='unfulfilled', max_length=32)),
                ('user_email', models.EmailField(blank=True, default='', max_length=254)),
                ('token', models.CharField(blank=True, max_length=36, unique=True)),
                ('checkout_token', models.CharField(blank=True, max_length=36)),
                ('shipping_method', models.CharField(choices=[('post', 'Post'), ('bike_delivery', 'Bike Delivery'), ('pickup', 'Pickup')], default='post', max_length=100)),
                ('shipping_cost', models.DecimalField(decimal_places=0, default=0, editable=False, max_digits=12)),
                ('total_net_amount', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('discount', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('customer_note', models.TextField(blank=True, default='')),
                ('weight', models.IntegerField(blank=True, default=0)),
                ('billing_address', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='account.address')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='account.customuser')),
                ('shipping_address', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='account.address')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_orders', to='account.customuser')),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
    ]
