# Generated by Django 4.0 on 2021-12-25 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_orderline_discount_alter_orderline_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderline',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True),
        ),
    ]
