# Generated by Django 4.0 on 2022-01-01 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_alter_product_product_type'),
        ('orders', '0004_alter_orderline_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderline',
            name='good',
        ),
        migrations.AddField(
            model_name='orderline',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_lines', to='products.product'),
        ),
    ]
