# Generated by Django 4.0.1 on 2022-01-11 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_orderline_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_gift',
            field=models.BooleanField(default=False),
        ),
    ]
