# Generated by Django 4.0.1 on 2022-01-15 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_rename_total_order_payable_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderline',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
