# Generated by Django 4.0.1 on 2022-01-27 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_order_approver'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='channel',
            field=models.CharField(choices=[('store', 'Store'), ('instagram', 'Instagram'), ('telegram', 'Telegram'), ('twitter', 'Twitter'), ('Website', 'Website'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
