# Generated by Django 4.0.1 on 2022-01-27 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_order_channel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='channel',
            field=models.CharField(choices=[('cashier', 'Cashier'), ('instagram', 'Instagram'), ('telegram', 'Telegram'), ('twitter', 'Twitter'), ('Website', 'Website'), ('other', 'Other')], default='cashier', max_length=50),
        ),
    ]
