# Generated by Django 4.0.1 on 2022-01-27 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_alter_order_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='approved_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
