# Generated by Django 4.0.1 on 2022-01-31 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_alter_order_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderline',
            name='variation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
