# Generated by Django 4.0.1 on 2022-02-03 08:27

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_product_publisher_2'),
        ('orders', '0020_purchase'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('discount', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('discount_percent', models.DecimalField(blank=True, decimal_places=0, default=Decimal('0'), max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('variation', models.CharField(blank=True, max_length=50, null=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_lines', to='products.product')),
                ('purchase', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='orders.purchase')),
            ],
            options={
                'ordering': ('-product',),
            },
        ),
    ]
