# Generated by Django 4.0.1 on 2022-02-07 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_alter_order_billing_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='deadline_days',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
