# Generated by Django 4.0.1 on 2022-02-08 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_purchase_deadline_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderline',
            name='shipped',
            field=models.BooleanField(default=False),
        ),
    ]
