# Generated by Django 4.0.1 on 2022-02-08 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0024_orderline_shipped'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderline',
            name='shipped_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
