# Generated by Django 4.0.1 on 2022-02-09 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0025_orderline_shipped_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='sipped_code',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
    ]
