# Generated by Django 4.0.1 on 2022-02-09 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0026_order_sipped_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='sipped_code',
            new_name='shipped_code',
        ),
    ]
