# Generated by Django 4.0.2 on 2022-02-19 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0029_alter_purchaseline_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='credit',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='order',
            name='pay_by_credit',
            field=models.BooleanField(default=False),
        ),
    ]
