# Generated by Django 4.0.2 on 2022-02-21 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0030_order_credit_order_pay_by_credit'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='orderline',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='purchaseline',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
