# Generated by Django 4.0.2 on 2022-02-23 17:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_alter_address_house_number_alter_address_house_unit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0032_purchase_paper_invoice_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalOrder',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('client_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, default='', max_length=128, region=None)),
                ('created', models.DateTimeField(blank=True, editable=False)),
                ('updated', models.DateTimeField(blank=True, editable=False)),
                ('approved_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('paid', 'Paid'), ('approved', 'Approved'), ('unfulfilled', 'Unfulfilled'), ('fulfilled', 'Fulfilled'), ('canceled', 'Canceled')], default='draft', max_length=32)),
                ('channel', models.CharField(choices=[('cashier', 'Cashier'), ('instagram', 'Instagram'), ('telegram', 'Telegram'), ('twitter', 'Twitter'), ('Website', 'Website'), ('other', 'Other')], default='cashier', max_length=50)),
                ('user_email', models.EmailField(blank=True, default='', max_length=254)),
                ('token', models.CharField(blank=True, db_index=True, max_length=36)),
                ('checkout_token', models.CharField(blank=True, max_length=36)),
                ('shipping_method', models.CharField(choices=[('post', 'Post'), ('bike_delivery', 'Bike Delivery'), ('pickup', 'Pickup')], default='post', max_length=100)),
                ('shipping_cost', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('shipped_code', models.CharField(blank=True, max_length=24, null=True)),
                ('shipping_status', models.CharField(blank=True, choices=[('', ''), ('semi', 'Semi shipped'), ('full', 'Fully Shipped')], default='', max_length=50, null=True)),
                ('total_cost', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('total_cost_after_discount', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('discount', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('payable', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('customer_note', models.TextField(blank=True, default='')),
                ('weight', models.IntegerField(blank=True, default=0)),
                ('quantity', models.IntegerField(default=0)),
                ('is_gift', models.BooleanField(default=False)),
                ('paid', models.BooleanField(default=False)),
                ('pay_by_credit', models.BooleanField(default=False)),
                ('credit', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('active', models.BooleanField(default=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('approver', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('billing_address', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='account.address')),
                ('client', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('shipping_address', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='account.address')),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical order',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
