# Generated by Django 4.0.2 on 2022-02-24 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0034_historicalorder_pay_receipt_order_pay_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorder',
            name='shipping_time',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_time',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
