# Generated by Django 4.0.2 on 2022-02-24 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0035_historicalorder_shipping_time_order_shipping_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='discount_percent',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
