# Generated by Django 4.0.2 on 2022-02-24 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0037_alter_purchase_discount_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='discount_percent',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
    ]
