# Generated by Django 4.0.2 on 2022-03-03 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0044_alter_purchaseline_discount_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorder',
            name='is_packaged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalorder',
            name='packaged_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='is_packaged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='packaged_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
