# Generated by Django 4.0.2 on 2022-03-06 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0045_historicalorder_is_packaged_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderline',
            name='cost_after_discount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
    ]
