# Generated by Django 4.0.2 on 2022-03-14 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0049_historicalorder_full_shipped_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalorder',
            name='channel',
            field=models.CharField(choices=[('cashier', 'Cashier'), ('instagram', 'Instagram'), ('insta_damavand', 'Insta-Damavand'), ('telegram', 'Telegram'), ('twitter', 'Twitter'), ('Website', 'Website'), ('other', 'Other')], default='cashier', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='channel',
            field=models.CharField(choices=[('cashier', 'Cashier'), ('instagram', 'Instagram'), ('insta_damavand', 'Insta-Damavand'), ('telegram', 'Telegram'), ('twitter', 'Twitter'), ('Website', 'Website'), ('other', 'Other')], default='cashier', max_length=50),
        ),
    ]
