# Generated by Django 4.0 on 2021-12-14 11:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_short_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='publish_year',
            field=models.IntegerField(blank=True, default=1400, null=True, validators=[django.core.validators.MinValueValidator(1233), django.core.validators.MaxValueValidator(1400)]),
        ),
    ]
