# Generated by Django 4.0 on 2021-12-18 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_importsession'),
        ('products', '0006_product_author_product_edition_product_illustrator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='import_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='files.importsession'),
        ),
    ]
