# Generated by Django 4.0 on 2021-12-21 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_good_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='good',
            name='cover_type',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='good',
            name='edition',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='good',
            name='purchase_price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
    ]
