# Generated by Django 4.0 on 2021-12-21 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_good_available_good_cover_type_good_edition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='state',
            field=models.CharField(blank=True, choices=[('new', 'New'), ('used', 'Used')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='state',
            field=models.CharField(choices=[('new', 'New'), ('used', 'Used')], default='new', max_length=10),
        ),
    ]
