# Generated by Django 4.0 on 2021-12-21 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_good_state_alter_product_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='state',
            field=models.CharField(choices=[('new', 'New'), ('used', 'Used')], default='new', max_length=10),
        ),
    ]
