# Generated by Django 4.0 on 2021-12-30 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_product_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-updated', '-created')},
        ),
        migrations.AddField(
            model_name='product',
            name='about',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='admin_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='age_range',
            field=models.CharField(choices=[('1', '0-2'), ('2', '2-4'), ('3', '4-6'), ('4', '6-8'), ('5', '8-10')], default='', max_length=150),
        ),
        migrations.AddField(
            model_name='product',
            name='author_latin_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='latin_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='page_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='zero_stock',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='zero_stock_limit',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
