# Generated by Django 4.0 on 2021-12-30 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_product_options_product_about_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='age_range',
            field=models.CharField(choices=[('-', ''), ('1', '0-2'), ('2', '2-4'), ('3', '4-6'), ('4', '6-8'), ('5', '8-10')], default='', max_length=150),
        ),
    ]
