# Generated by Django 4.0.1 on 2022-01-18 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_category_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='available_in_store',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='available_online',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='has_other_prices',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='store_positon',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='vendor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
