# Generated by Django 4.0.1 on 2022-01-26 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_product_price_1_product_stock_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='isbn_9',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
