# Generated by Django 4.0.1 on 2022-02-17 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0031_product_collection_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='collection_parent',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
