# Generated by Django 4.0.2 on 2022-02-18 14:54

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0005_importsession_quantity'),
        ('account', '0014_rename_number_address_house_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0032_alter_product_collection_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalProduct',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=500)),
                ('slug', models.SlugField(allow_unicode=True, max_length=550)),
                ('barcode_number', models.CharField(blank=True, max_length=13, null=True)),
                ('isbn', models.CharField(blank=True, max_length=13, null=True)),
                ('isbn_9', models.CharField(blank=True, max_length=9, null=True)),
                ('author', models.CharField(blank=True, max_length=200, null=True)),
                ('translator', models.CharField(blank=True, max_length=200, null=True)),
                ('illustrator', models.CharField(blank=True, max_length=200, null=True)),
                ('latin_name', models.CharField(blank=True, max_length=300, null=True)),
                ('author_latin_name', models.CharField(blank=True, max_length=300, null=True)),
                ('image', models.TextField(blank=True, max_length=100)),
                ('image_alt', models.CharField(blank=True, max_length=300, null=True)),
                ('about', models.CharField(blank=True, max_length=150, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_collection', models.BooleanField(default=False)),
                ('collection_set', models.TextField(blank=True, null=True)),
                ('collection_parent', models.CharField(blank=True, max_length=13, null=True)),
                ('age_range', models.CharField(choices=[('-', ''), ('1', '0-2'), ('2', '2-4'), ('3', '4-6'), ('4', '6-8'), ('5', '8-10')], default='', max_length=150)),
                ('stock', models.IntegerField(default=0)),
                ('zero_stock', models.BooleanField(default=False)),
                ('zero_stock_limit', models.IntegerField(blank=True, null=True)),
                ('product_type', models.CharField(blank=True, choices=[('book', 'Book'), ('craft', 'Craft')], max_length=100, null=True)),
                ('state', models.CharField(choices=[('new', 'New'), ('used', 'Used')], default='new', max_length=10)),
                ('weight', models.FloatField(blank=True, default=0, null=True)),
                ('size', models.CharField(blank=True, max_length=250, null=True)),
                ('cover_type', models.CharField(blank=True, max_length=250, null=True)),
                ('page_number', models.IntegerField(default=0)),
                ('publisher', models.CharField(blank=True, max_length=250, null=True)),
                ('publisher_2', models.CharField(blank=True, max_length=250, null=True)),
                ('publish_year', models.IntegerField(blank=True, default=1400, null=True, validators=[django.core.validators.MinValueValidator(1233), django.core.validators.MaxValueValidator(1400)])),
                ('edition', models.IntegerField(blank=True, null=True)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('has_other_prices', models.BooleanField(default=False)),
                ('price_1', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('stock_1', models.IntegerField(default=0)),
                ('price_2', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('stock_2', models.IntegerField(default=0)),
                ('price_3', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('stock_3', models.IntegerField(default=0)),
                ('price_4', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('stock_4', models.IntegerField(default=0)),
                ('price_5', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('stock_5', models.IntegerField(default=0)),
                ('price_used', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('stock_used', models.IntegerField(default=0)),
                ('store_positon', models.CharField(blank=True, max_length=8, null=True)),
                ('admin_note', models.TextField(blank=True, null=True)),
                ('available', models.BooleanField(default=True)),
                ('available_in_store', models.BooleanField(default=True)),
                ('available_online', models.BooleanField(default=True)),
                ('created', models.DateTimeField(blank=True, editable=False)),
                ('updated', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('category', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='products.category')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('import_session', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='files.importsession')),
                ('vendor', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='account.vendor')),
            ],
            options={
                'verbose_name': 'historical product',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
