# Generated by Django 4.0.2 on 2022-02-26 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_customuser_social_media_name'),
        ('products', '0033_historicalproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='vendors',
            field=models.ManyToManyField(blank=True, null=True, related_name='products_vendor', to='account.Vendor'),
        ),
    ]
