# Generated by Django 4.0.2 on 2022-02-26 18:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0036_craft_historicalcraft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='craft',
            name='barcode_number',
            field=models.CharField(default=django.utils.timezone.now, max_length=13, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicalcraft',
            name='barcode_number',
            field=models.CharField(db_index=True, default=django.utils.timezone.now, max_length=13),
            preserve_default=False,
        ),
    ]
