# Generated by Django 4.0.2 on 2022-03-06 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0038_historicalproduct_craft_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproduct',
            name='collection_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='number_in_collection',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='collection_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='number_in_collection',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
