# Generated by Django 4.0.2 on 2022-03-24 06:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0039_historicalproduct_collection_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproduct',
            name='publish_year',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1233), django.core.validators.MaxValueValidator(1400)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='publish_year',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1233), django.core.validators.MaxValueValidator(1400)]),
        ),
    ]
