# Generated by Django 4.0.2 on 2022-04-07 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0046_publisher'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproduct',
            name='pub_1',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='products.publisher'),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='pub_2',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='products.publisher'),
        ),
        migrations.AddField(
            model_name='product',
            name='pub_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productPub_1', to='products.publisher'),
        ),
        migrations.AddField(
            model_name='product',
            name='pub_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productPub_2', to='products.publisher'),
        ),
    ]
