# Generated by Django 4.0.2 on 2022-04-08 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0047_historicalproduct_pub_1_historicalproduct_pub_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='product_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
